/**
 * Writes public/sw.js with a versioned cache list of WebPerl + perl assets.
 */
const fs = require("fs");
const path = require("path");
const { ENGINE_ASSET_PATHS } = require("./engine-assets.cjs");

const pkg = require("../package.json");
const CACHE_NAME = `latexdiff-engine-${pkg.version}`;
const OUT = path.resolve(__dirname, "../public/sw.js");

const sw = `/* Generated by scripts/generate-sw.cjs — do not edit by hand */
const CACHE_NAME = ${JSON.stringify(CACHE_NAME)};
const ASSET_PATHS = ${JSON.stringify(ENGINE_ASSET_PATHS, null, 2)};

function assetUrls() {
  const base = new URL("./", self.location.href);
  return ASSET_PATHS.map((p) => new URL(p, base).href);
}

function isEngineRequest(url) {
  return url.pathname.includes("/core/webperl/") || url.pathname.includes("/core/perl/");
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) => cache.addAll(assetUrls()))
      .then(() => self.skipWaiting())
      .catch((err) => console.error("[sw] install cache failed", err)),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== "GET" || !isEngineRequest(url)) {
    return;
  }

  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) {
        return cached;
      }
      return fetch(event.request).then((response) => {
        if (!response.ok) {
          return response;
        }
        const copy = response.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
        return response;
      });
    }),
  );
});
`;

fs.writeFileSync(OUT, sw);
console.log(`✓ Wrote ${OUT} (cache: ${CACHE_NAME}, ${ENGINE_ASSET_PATHS.length} assets)`);
